### ISSUE TITLE
Should escaping be done on stored data or in output

### ISSUE THREAD

**Issue by getub** [toastdriven/django-haystack#1096]
If I understand the [example here](http://django-haystack.readthedocs.org/en/latest/searchindex_api.html?highlight=safe#stored-indexed-fields) correctly, 

The data in template `search/indexes/myapp/note_rendered.txt` is autoescaped before storing in the index. When the search results need to be output, the `safe` filter is used to unescape it in `search/search.html`. However, from what I've read/seen in many projects, it's better to store raw data in database (index in this case) and the escaping should be done while rendering (depending on the context). Are we doing the reverse in django-haystack i.e. escape while storing & unescape as & when needed with `safe` tag? Any particular reason for that?

P.S. Where's the documentation for available tags that can be used. Or will all django template tags work?

**Comment by getub** [comment]
Hi @acdha : Could you comment on this core auto-escaping behavior ? I've searched a lot but couldn't find a satisfactory answer. You are quite familiar and I'm hoping you can shed some light. Sorry for the interrupt.

**Comment by acdha** [comment]
This seems like a better question for the haystack users mailing list rather than an issue unless you wanted to work on a documentation pull request for this.

To answer the questions:
* It's reusing the standard Django templating engine, so you can use any template tag library available in your project
* The escaping behaviour is definitely a bit confusing because we're effectively repeating the same process twice:

1. Retrieve data
2. Render
3. Send to search engine
4. Retrieve data
5. Render
6. Send to browser

Haystack should probably have the option of rendering the field templates with autoescape disabled so you don't need to `|safe` everything which contains HTML special characters but since this has been the behaviour for so long we'd probably need to make that an opt-in setting in case anyone has `|safe` in their search results template.
