### ISSUE TITLE
Fallback in case of Elasticsearch failure

### ISSUE THREAD

**Issue by addremove** [toastdriven/django-haystack#1129]
I want to implement a fallback database full text search (even if it's slow) in case Elasticsearch server has a timeout error or failure. I was thinking of wrapping `SearchQuerySet().models(MyModel)` in a `try/except` block and look for `ConnectionError` or `ConnectTimeoutError` 

The problem is, despite setting a `TIMEOUT` of 1 second (in haystack), I've to wait for 3-4 seconds before I see an exception. Is there a way I can know within milliseconds if ES is failing and use a direct database search? My use case is autocomplete search where I want the user to have a seamless experience even if ES is unavailable. Waiting for a few seconds seems too long. 

Maybe I'm thinking along the wrong lines and ES failure should be handled in a different way or it's not an issue. Please enlighten me about how people deal with this.

**Comment by phill-tornroth** [comment]
I use ES (and previously Solr) extensively for autocompletes and in my experience it's easier to keep those services up via redundancies in the way you deploy them than it is to make things work seamlessly against two totally different systems. Serving autocompletes from the database is often painful to do efficiently, and I assume that's true for you as well otherwise why would you be using ES in the first place?

That said, if you really want to do this you could switch them pro-actively by monitoring your ES' cluster health and your ability to connect to it, and state-fully redirect all of your queries to the database until your health-check turns green again.

**Comment by phill-tornroth** [comment]
Also, I think this is a question better asked on the haystack-users list. It's not really an issue unless it's a request for sub-second timeout support, which probably still makes sense to ask about on the list first.

**Comment by addremove** [comment]
Agreed, thanks for sharing your experience.
